name: Build

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: src
        cache-all-crates: true

    - name: Cargo build
      run: cargo build --release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: .
